# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: echoService.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("echoService.proto", :syntax => :proto3) do
    add_message "GetEchoMessage" do
      optional :target_echo, :string, 1
    end
    add_message "EchoResponse" do
      optional :input, :string, 1
    end
  end
end

GetEchoMessage = Google::Protobuf::DescriptorPool.generated_pool.lookup("GetEchoMessage").msgclass
EchoResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("EchoResponse").msgclass
